### ISSUE TITLE
Random crashes with prefabs enabled.

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/o3de-humanworker-gem#15]
Roscon demo 2023 on development branch is unstable (crashes) when prefabs with NPCs are enabled. 

I used stabilization branch of this repo.

**Comment by jhanca-robotecai** [comment]
I saw you made two PRs to this repo and to ROSCon2023 repo. Is this issue still present?

**Comment by michalpelka** [comment]
I think we can close it, I did not reproduce it lately. Probably I used older version of development.
